# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aogaki/Simulation/GeDetForGBS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aogaki/Simulation/GeDetForGBS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aogaki/Simulation/GeDetForGBS/CMakeFiles /home/aogaki/Simulation/GeDetForGBS/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aogaki/Simulation/GeDetForGBS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyPro

# Build rule for target.
MyPro: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MyPro
.PHONY : MyPro

# fast build rule for target.
MyPro/fast:
	$(MAKE) -f CMakeFiles/MyPro.dir/build.make CMakeFiles/MyPro.dir/build
.PHONY : MyPro/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/build
.PHONY : example/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/main.cpp.s
.PHONY : main.cpp.s

src/GDActionInitialization.o: src/GDActionInitialization.cpp.o

.PHONY : src/GDActionInitialization.o

# target to build an object file
src/GDActionInitialization.cpp.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDActionInitialization.cpp.o
.PHONY : src/GDActionInitialization.cpp.o

src/GDActionInitialization.i: src/GDActionInitialization.cpp.i

.PHONY : src/GDActionInitialization.i

# target to preprocess a source file
src/GDActionInitialization.cpp.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDActionInitialization.cpp.i
.PHONY : src/GDActionInitialization.cpp.i

src/GDActionInitialization.s: src/GDActionInitialization.cpp.s

.PHONY : src/GDActionInitialization.s

# target to generate assembly for a file
src/GDActionInitialization.cpp.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDActionInitialization.cpp.s
.PHONY : src/GDActionInitialization.cpp.s

src/GDDetectorConstruction.o: src/GDDetectorConstruction.cpp.o

.PHONY : src/GDDetectorConstruction.o

# target to build an object file
src/GDDetectorConstruction.cpp.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDDetectorConstruction.cpp.o
.PHONY : src/GDDetectorConstruction.cpp.o

src/GDDetectorConstruction.i: src/GDDetectorConstruction.cpp.i

.PHONY : src/GDDetectorConstruction.i

# target to preprocess a source file
src/GDDetectorConstruction.cpp.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDDetectorConstruction.cpp.i
.PHONY : src/GDDetectorConstruction.cpp.i

src/GDDetectorConstruction.s: src/GDDetectorConstruction.cpp.s

.PHONY : src/GDDetectorConstruction.s

# target to generate assembly for a file
src/GDDetectorConstruction.cpp.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDDetectorConstruction.cpp.s
.PHONY : src/GDDetectorConstruction.cpp.s

src/GDEventAction.o: src/GDEventAction.cpp.o

.PHONY : src/GDEventAction.o

# target to build an object file
src/GDEventAction.cpp.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDEventAction.cpp.o
.PHONY : src/GDEventAction.cpp.o

src/GDEventAction.i: src/GDEventAction.cpp.i

.PHONY : src/GDEventAction.i

# target to preprocess a source file
src/GDEventAction.cpp.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDEventAction.cpp.i
.PHONY : src/GDEventAction.cpp.i

src/GDEventAction.s: src/GDEventAction.cpp.s

.PHONY : src/GDEventAction.s

# target to generate assembly for a file
src/GDEventAction.cpp.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDEventAction.cpp.s
.PHONY : src/GDEventAction.cpp.s

src/GDHit.o: src/GDHit.cpp.o

.PHONY : src/GDHit.o

# target to build an object file
src/GDHit.cpp.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDHit.cpp.o
.PHONY : src/GDHit.cpp.o

src/GDHit.i: src/GDHit.cpp.i

.PHONY : src/GDHit.i

# target to preprocess a source file
src/GDHit.cpp.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDHit.cpp.i
.PHONY : src/GDHit.cpp.i

src/GDHit.s: src/GDHit.cpp.s

.PHONY : src/GDHit.s

# target to generate assembly for a file
src/GDHit.cpp.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDHit.cpp.s
.PHONY : src/GDHit.cpp.s

src/GDPhysicsList.o: src/GDPhysicsList.cpp.o

.PHONY : src/GDPhysicsList.o

# target to build an object file
src/GDPhysicsList.cpp.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDPhysicsList.cpp.o
.PHONY : src/GDPhysicsList.cpp.o

src/GDPhysicsList.i: src/GDPhysicsList.cpp.i

.PHONY : src/GDPhysicsList.i

# target to preprocess a source file
src/GDPhysicsList.cpp.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDPhysicsList.cpp.i
.PHONY : src/GDPhysicsList.cpp.i

src/GDPhysicsList.s: src/GDPhysicsList.cpp.s

.PHONY : src/GDPhysicsList.s

# target to generate assembly for a file
src/GDPhysicsList.cpp.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDPhysicsList.cpp.s
.PHONY : src/GDPhysicsList.cpp.s

src/GDPrimaryGeneratorAction.o: src/GDPrimaryGeneratorAction.cpp.o

.PHONY : src/GDPrimaryGeneratorAction.o

# target to build an object file
src/GDPrimaryGeneratorAction.cpp.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDPrimaryGeneratorAction.cpp.o
.PHONY : src/GDPrimaryGeneratorAction.cpp.o

src/GDPrimaryGeneratorAction.i: src/GDPrimaryGeneratorAction.cpp.i

.PHONY : src/GDPrimaryGeneratorAction.i

# target to preprocess a source file
src/GDPrimaryGeneratorAction.cpp.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDPrimaryGeneratorAction.cpp.i
.PHONY : src/GDPrimaryGeneratorAction.cpp.i

src/GDPrimaryGeneratorAction.s: src/GDPrimaryGeneratorAction.cpp.s

.PHONY : src/GDPrimaryGeneratorAction.s

# target to generate assembly for a file
src/GDPrimaryGeneratorAction.cpp.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDPrimaryGeneratorAction.cpp.s
.PHONY : src/GDPrimaryGeneratorAction.cpp.s

src/GDRunAction.o: src/GDRunAction.cpp.o

.PHONY : src/GDRunAction.o

# target to build an object file
src/GDRunAction.cpp.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDRunAction.cpp.o
.PHONY : src/GDRunAction.cpp.o

src/GDRunAction.i: src/GDRunAction.cpp.i

.PHONY : src/GDRunAction.i

# target to preprocess a source file
src/GDRunAction.cpp.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDRunAction.cpp.i
.PHONY : src/GDRunAction.cpp.i

src/GDRunAction.s: src/GDRunAction.cpp.s

.PHONY : src/GDRunAction.s

# target to generate assembly for a file
src/GDRunAction.cpp.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDRunAction.cpp.s
.PHONY : src/GDRunAction.cpp.s

src/GDSD.o: src/GDSD.cpp.o

.PHONY : src/GDSD.o

# target to build an object file
src/GDSD.cpp.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDSD.cpp.o
.PHONY : src/GDSD.cpp.o

src/GDSD.i: src/GDSD.cpp.i

.PHONY : src/GDSD.i

# target to preprocess a source file
src/GDSD.cpp.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDSD.cpp.i
.PHONY : src/GDSD.cpp.i

src/GDSD.s: src/GDSD.cpp.s

.PHONY : src/GDSD.s

# target to generate assembly for a file
src/GDSD.cpp.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/GDSD.cpp.s
.PHONY : src/GDSD.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... MyPro"
	@echo "... example"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/GDActionInitialization.o"
	@echo "... src/GDActionInitialization.i"
	@echo "... src/GDActionInitialization.s"
	@echo "... src/GDDetectorConstruction.o"
	@echo "... src/GDDetectorConstruction.i"
	@echo "... src/GDDetectorConstruction.s"
	@echo "... src/GDEventAction.o"
	@echo "... src/GDEventAction.i"
	@echo "... src/GDEventAction.s"
	@echo "... src/GDHit.o"
	@echo "... src/GDHit.i"
	@echo "... src/GDHit.s"
	@echo "... src/GDPhysicsList.o"
	@echo "... src/GDPhysicsList.i"
	@echo "... src/GDPhysicsList.s"
	@echo "... src/GDPrimaryGeneratorAction.o"
	@echo "... src/GDPrimaryGeneratorAction.i"
	@echo "... src/GDPrimaryGeneratorAction.s"
	@echo "... src/GDRunAction.o"
	@echo "... src/GDRunAction.i"
	@echo "... src/GDRunAction.s"
	@echo "... src/GDSD.o"
	@echo "... src/GDSD.i"
	@echo "... src/GDSD.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

